// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package module.proxies;

public class CreditCardComponent implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject creditCardComponentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Module.CreditCardComponent";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IsFlipped("IsFlipped"),
		CreditCardComponent_CreditCardInfo("Module.CreditCardComponent_CreditCardInfo");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CreditCardComponent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CreditCardComponent(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject creditCardComponentMendixObject)
	{
		if (creditCardComponentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, creditCardComponentMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.creditCardComponentMendixObject = creditCardComponentMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static module.proxies.CreditCardComponent initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new module.proxies.CreditCardComponent(context, mendixObject);
	}

	public static module.proxies.CreditCardComponent load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return module.proxies.CreditCardComponent.initialize(context, mendixObject);
	}

	/**
	 * @return value of IsFlipped
	 */
	public final java.lang.Boolean getIsFlipped()
	{
		return getIsFlipped(getContext());
	}

	/**
	 * @param context
	 * @return value of IsFlipped
	 */
	public final java.lang.Boolean getIsFlipped(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsFlipped.toString());
	}

	/**
	 * Set value of IsFlipped
	 * @param isflipped
	 */
	public final void setIsFlipped(java.lang.Boolean isflipped)
	{
		setIsFlipped(getContext(), isflipped);
	}

	/**
	 * Set value of IsFlipped
	 * @param context
	 * @param isflipped
	 */
	public final void setIsFlipped(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isflipped)
	{
		getMendixObject().setValue(context, MemberNames.IsFlipped.toString(), isflipped);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CreditCardComponent_CreditCardInfo
	 */
	public final module.proxies.CreditCardInfo getCreditCardComponent_CreditCardInfo() throws com.mendix.core.CoreException
	{
		return getCreditCardComponent_CreditCardInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of CreditCardComponent_CreditCardInfo
	 * @throws com.mendix.core.CoreException
	 */
	public final module.proxies.CreditCardInfo getCreditCardComponent_CreditCardInfo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		module.proxies.CreditCardInfo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CreditCardComponent_CreditCardInfo.toString());
		if (identifier != null) {
			result = module.proxies.CreditCardInfo.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CreditCardComponent_CreditCardInfo
	 * @param creditcardcomponent_creditcardinfo
	 */
	public final void setCreditCardComponent_CreditCardInfo(module.proxies.CreditCardInfo creditcardcomponent_creditcardinfo)
	{
		setCreditCardComponent_CreditCardInfo(getContext(), creditcardcomponent_creditcardinfo);
	}

	/**
	 * Set value of CreditCardComponent_CreditCardInfo
	 * @param context
	 * @param creditcardcomponent_creditcardinfo
	 */
	public final void setCreditCardComponent_CreditCardInfo(com.mendix.systemwideinterfaces.core.IContext context, module.proxies.CreditCardInfo creditcardcomponent_creditcardinfo)
	{
		if (creditcardcomponent_creditcardinfo == null) {
			getMendixObject().setValue(context, MemberNames.CreditCardComponent_CreditCardInfo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CreditCardComponent_CreditCardInfo.toString(), creditcardcomponent_creditcardinfo.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return creditCardComponentMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final module.proxies.CreditCardComponent that = (module.proxies.CreditCardComponent) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
